version: '3.4'

networks:
  gback:
    driver: bridge

services:
  backend:
    image: ghcr.io/waltermblair/clj-back:release
    container_name: backend
    networks:
      - gback
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - gback
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: gback
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./resources/mysql/init:/docker-entrypoint-initdb.d
